### ISSUE TITLE
Reduce dependencies of Line SDK

### ISSUE THREAD

**Issue by fornewid** [line/line-sdk-android#1]
## What did you do?

I try to install Line SDK 5.0.0 in my app for line login.

## What did you expect?

Add the following code only.
```
implementation(name:'line-sdk-5.0.0', ext:'aar')
```

## What happened actually?

Too much dependencies are exists.

I think, the following libs are needed for Line SDK only.
```
implementation('com.madgag.spongycastle:prov:1.58.0.0') {
    exclude group: 'junit', module: 'junit'
}
runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.10.5'
runtimeOnly ('io.jsonwebtoken:jjwt-orgjson:0.10.5') {
    exclude group: 'org.json', module: 'json' //provided by Android natively
}
```

And at 'kotlin only' projects, the followings are also unneeded.
```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```

## Your environment?

> 

## Sample project

>

**Comment by LiYing2010** [comment]
1.  about `spongycastle`

> I think, the following libs are needed for Line SDK only.
> implementation('com.madgag.spongycastle:prov:1.58.0.0') {
>     exclude group: 'junit', module: 'junit'
> }

This lib is used here:
https://github.com/line/line-sdk-android/blob/master/line-sdk/src/main/java/com/linecorp/linesdk/internal/nwclient/OpenIdSigningKeyResolver.java

2. about `jsonwebtoken`
> runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.10.5'
> runtimeOnly ('io.jsonwebtoken:jjwt-orgjson:0.10.5') {
>     exclude group: 'org.json', module: 'json' //provided by Android natively
> }

This lib is used here:
https://github.com/line/line-sdk-android/blob/master/line-sdk/src/main/java/com/linecorp/linesdk/internal/nwclient/IdTokenParser.java

Both of them are needed to parse `IdToken`, which is part of `Getting an access token` API response.
This `IdToken` is 

pelase refer to the following LINE Login Documents:
https://developers.line.biz/en/docs/line-login/web/integrate-line-login/#spy-getting-an-access-token
https://developers.line.biz/en/docs/line-login/web/integrate-line-login/#id-tokens

**Comment by LiYing2010** [comment]
hi @fornewid :
May I ask you if you agree with my explain about these 2 libs?
If it's OK, I like to mark this issue as `wontfix`,  and close it.

**Comment by fornewid** [comment]
OK, I understand and close this.
But please re-consider my request later if you can.
