### ISSUE TITLE
An error will occur in the unity 2018 building. What kind of cause can be considered?

### ISSUE THREAD

**Issue by BigTreeeChen** [line/line-sdk-android#105]
main error msg: “Landroid/view/View$OnClickListener; to set up parameter 1 for com/linecorp/linesdk”

just the same as "https://github.com/line/line-sdk-android/issues/7"

I successfully build my.aar that use linesdk-5.0.1.aar，but when i use my.aar to build my apk in unity, error above occur，i use gradle.3.1.2 and android studio 3.1.2。
I really want to know what happens.

**Comment by plateaukao** [comment]
Hi, @BigTreeeChen 
Please follow issue template to provide necessary information, so that we can help to investigate this issue. Also, Please use the latest version instead, since linesdk-5.0.1 is a bit old now.

**Comment by plateaukao** [comment]
close due to this issue is on very old version and no further information is provided.
