### ISSUE TITLE
samsung Galaxy C5  Android8.0 Automatically cancel login

### ISSUE THREAD

**Issue by trrying** [line/line-sdk-android#11]
samsung Galaxy C5  Android8.0 Automatically cancel login

In the mobile phone Samsung Galaxy C5 Android8.0 use demo login, when the Line app is open, the normal authorization login, when the Line app is not running, the authorization will be adjusted, and then jump back, result.getResponseCode() = CANCEL.

**Comment by plateaukao** [comment]
Close due to this issue is created long time ago.  If this is still an issue, please open a new issue and attach necessary information. Thanks.
