### ISSUE TITLE
Android 12 Device LINE app-to-app login not working

### ISSUE THREAD

**Issue by kjt0429** [line/line-sdk-android#115]
## Is it a security issue?

If you believe you have discovered a vulnerability or have an issue related to security, please send us a mail to dl_oss_dev@linecorp.com instead of opening a public issue.

## What did you do?

>  app-to-app login (LineLoginApi.getLoginIntent)

## What did you expect?

> The LINE app login flow starts, and the UI is exposed to the user to check the login consent.

## What happened actually?

> just error popup (korean: 오류 정상적으로 처리하지 못하였습니다.)

## Your environment?

> Android 12 device, targetSDKversion 30 app

## Sample project

> sorry. this is only company test app, and it cannot be leaked to the outside.

(+)
in Android 12 device, I tried to web log-in. However, the web-login API(getLoginIntentWithoutLineAppAuth) does not work.
this api is not working all device. (android 10, 11, 12)

**Comment by plateaukao** [comment]
Hi, @kjt0429 

May I know which version of line-sdk do you use? Have you tried integrating with the latest version of it?

**Comment by plateaukao** [comment]
close due to no further information provided
