### ISSUE TITLE
[Q OS] LineLoginApi.getLoginIntent(...) is not working properly

### ISSUE THREAD

**Issue by fornewid** [line/line-sdk-android#12]
At Q OS, `LineLoginApi.getLoginIntent(...)` is not working properly.
If a user clicks "Allow" button, **"Grant permission?"** screen is shown again.
Please check this operation. :)

- Device: Pixel 2
- Android Version: Q (QPP1.190205.018.B4)
- LINE App Version: 9.4.2

**Comment by plateaukao** [comment]
Thanks for reporting this issue. We will look into this issue soon.

**Comment by zhangjunwei369** [comment]
How do I fill it out?
![image](https://user-images.githubusercontent.com/22976155/74941823-aadc1400-542e-11ea-9286-67edd2e83312.png)

**Comment by plateaukao** [comment]
please remove all the ":" in SHA string, and try again.

**Comment by plateaukao** [comment]
Hi, @fornewid , does this issue still exist?

**Comment by fornewid** [comment]
Um.. it is difficult to check for personal reasons currently. 😭 
If it has been fixed, I think this issue can be closed. :)

**Comment by plateaukao** [comment]
Okay, I will close it now. If you still encounter the issue later on, please re-open it then.
