### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: com.linecorp.linesdk.auth.LineAuthenticationConfig

### ISSUE THREAD

**Issue by zx491102** [line/line-sdk-android#14]
05-12 05:19:17.821  1536  2494 E Parcel  : Class not found when unmarshalling: com.linecorp.linesdk.auth.LineAuthenticationConfig
05-12 05:19:17.821  1536  2494 E Parcel  : java.lang.ClassNotFoundException: com.linecorp.linesdk.auth.LineAuthenticationConfig
05-12 05:19:17.821  1536  2494 E Parcel  : 	at java.lang.Class.classForName(Native Method)
05-12 05:19:17.821  1536  2494 E Parcel  : 	at java.lang.Class.forName(Class.java:453)
05-12 05:19:17.821  1536  2494 E Parcel  : 	at android.os.Parcel.readParcelableCreator(Parcel.java:2834)
05-12 05:19:17.821  1536  2494 E Parcel  : 	at android.os.Parcel.readParcelable(Parcel.java:2788)
05-12 05:19:17.821  1536  2494 E Parcel  : 	at android.os.Parcel.readValue(Parcel.java:2691)
05-12 05:19:17.821  1536  2494 E Parcel  : 	at android.os.Parcel.readArrayMapInternal(Parcel.java:3058)
05-12 05:19:17.821  1536  2494 E Parcel  : 	at android.os.BaseBundle.unparcel(BaseBundle.java:257)
05-12 05:19:17.821  1536  2494 E Parcel  : 	at android.os.BaseBundle.getString(BaseBundle.java:1086)
05-12 05:19:17.821  1536  2494 E Parcel  : 	at android.content.Intent.getStringExtra(Intent.java:7706)
05-12 05:19:17.821  1536  2494 E Parcel  : 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:459)
05-12 05:19:17.821  1536  2494 E Parcel  : 	at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:410)
05-12 05:19:17.821  1536  2494 E Parcel  : 	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1277)
05-12 05:19:17.821  1536  2494 E Parcel  : 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5988)
05-12 05:19:17.821  1536  2494 E Parcel  : 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5841)
05-12 05:19:17.821  1536  2494 E Parcel  : 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:121)
05-12 05:19:17.821  1536  2494 E Parcel  : 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3818)
05-12 05:19:17.821  1536  2494 E Parcel  : 	at android.os.Binder.execTransact(Binder.java:682)
05-12 05:19:17.821  1536  2494 E Parcel  : Caused by: java.lang.ClassNotFoundException: com.linecorp.linesdk.auth.LineAuthenticationConfig
05-12 05:19:17.821  1536  2494 E Parcel  : 	at java.lang.Class.classForName(Native Method)
05-12 05:19:17.821  1536  2494 E Parcel  : 	at java.lang.BootClassLoader.findClass(ClassLoader.java:1355)
05-12 05:19:17.821  1536  2494 E Parcel  : 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:1415)
05-12 05:19:17.821  1536  2494 E Parcel  : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-12 05:19:17.821  1536  2494 E Parcel  : 	... 17 more
05-12 05:19:17.821  1536  2494 E Parcel  : Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
05-12 05:19:17.822  1536  2494 W Bundle  : Failed to parse Bundle, but defusing quietly
05-12 05:19:17.822  1536  2494 W Bundle  : android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.linecorp.linesdk.auth.LineAuthenticationConfig
05-12 05:19:17.822  1536  2494 W Bundle  : 	at android.os.Parcel.readParcelableCreator(Parcel.java:2862)
05-12 05:19:17.822  1536  2494 W Bundle  : 	at android.os.Parcel.readParcelable(Parcel.java:2788)
05-12 05:19:17.822  1536  2494 W Bundle  : 	at android.os.Parcel.readValue(Parcel.java:2691)
05-12 05:19:17.822  1536  2494 W Bundle  : 	at android.os.Parcel.readArrayMapInternal(Parcel.java:3058)
05-12 05:19:17.822  1536  2494 W Bundle  : 	at android.os.BaseBundle.unparcel(BaseBundle.java:257)
05-12 05:19:17.822  1536  2494 W Bundle  : 	at android.os.BaseBundle.getString(BaseBundle.java:1086)
05-12 05:19:17.822  1536  2494 W Bundle  : 	at android.content.Intent.getStringExtra(Intent.java:7706)
05-12 05:19:17.822  1536  2494 W Bundle  : 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:459)
05-12 05:19:17.822  1536  2494 W Bundle  : 	at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:410)
05-12 05:19:17.822  1536  2494 W Bundle  : 	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1277)
05-12 05:19:17.822  1536  2494 W Bundle  : 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5988)
05-12 05:19:17.822  1536  2494 W Bundle  : 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5841)
05-12 05:19:17.822  1536  2494 W Bundle  : 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:121)
05-12 05:19:17.822  1536  2494 W Bundle  : 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3818)
05-12 05:19:17.822  1536  2494 W Bundle  : 	at android.os.Binder.execTransact(Binder.java:682)
05-12 05:19:17.823  1536  2494 I ActivityManager: START u0 {act=null typ=null flg=0x0 cmp=ComponentInfo{com.netease.lrsjp.netease_global/com.linecorp.linesdk.auth.internal.LineAuthenticationActivity}} from uid 10495

**Comment by plateaukao** [comment]
Hi, @zx491102 

Could you provide more information by following the issue reporting template? So that we can investigate this symptom more easily. Thanks.

**Comment by plateaukao** [comment]
No further information is provided, so close for now.
