### ISSUE TITLE
line app在已经登录的情况下，我的应用程序调sdk登录，登录完成，无法返回我的应用程序

### ISSUE THREAD

**Issue by agni** [line/line-sdk-android#141]
line app在已经登录的情况下，我的应用程序调用sdk登录，登录完成，无法返回我的应用程序，要手动返回才行，如果line没打开，或者没登录的情况下，就没有问题，我使用的cocos creator接的sdk，麻烦官方帮忙解决下

**Comment by zhaohang-soul** [comment]
升级Android15后，我遇到同样的问题，你的问题当时解决了吗

**Comment by agni** [comment]
最终也没解决，后面那边不做了，就不管了。




Agni&nbsp;Wang
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "line/line-sdk-android"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月10日(星期三) 下午2:52
***@***.***&gt;;
抄送:&nbsp;"Agni ***@***.******@***.***&gt;;
主题:&nbsp;Re: [line/line-sdk-android] line app在已经登录的情况下，我的应用程序调sdk登录，登录完成，无法返回我的应用程序 (Issue #141)





 
升级Android15后，我遇到同样的问题，你的问题当时解决了吗

**Comment by zhaohang-soul** [comment]
好的谢谢

**Comment by YkSix** [comment]
@agni , @zhaohang-soul ,
Thanks for reporting this issue.
I have commented on the other issue that is the same as this one.
I will be closing this issue. For further discussion, please refer to the other issue page.
- https://github.com/line/line-sdk-android/issues/171

Thanks.
