### ISSUE TITLE
Could you tell me if there is sample code to get email ?

### ISSUE THREAD

**Issue by nrikiji** [line/line-sdk-android#22]
Could you tell me if there is sample code to get email ?

**Comment by LiYing2010** [comment]
1. an user's email can be retrieved from `IdToken`
https://github.com/line/line-sdk-android/blob/c6e7536799cc49b03ee4797266ff2f984a895a1c/line-sdk/src/main/java/com/linecorp/linesdk/LineIdToken.java#L268-L275


2. to get `IdToken`, you need to include scope `OPENID_CONNECT` and scope `OC_EMAIL` in your login parameters
https://github.com/line/line-sdk-android/blob/dbb2ae0fd85677d00554e437f16fd2bc23bb0f87/line-sdk/src/main/java/com/linecorp/linesdk/Scope.java#L49-L57

3. sample code can be found here:
https://github.com/line/line-sdk-android/blob/3e86b54433384950ceede9ae139a6d47ee21a391/app/src/main/java/com/linecorp/linesdktest/SignInFragment.java#L159

**Comment by LiYing2010** [comment]
there is a document about how to use LINE SDK for Android:
https://developers.line.biz/en/docs/android-sdk/integrate-line-login/

and about the IdToken, please refer to this document:
https://developers.line.biz/en/reference/android-sdk/reference/com/linecorp/linesdk/auth/LineLoginResult.html#getLineIdToken()

and:
https://developers.line.biz/en/reference/android-sdk/reference/com/linecorp/linesdk/LineIdToken.html

**Comment by nrikiji** [comment]
thanks!
