### ISSUE TITLE
How can I config redirect_uri in Line sdk?

### ISSUE THREAD

**Issue by BichAltplus** [line/line-sdk-android#65]
## Is it a security issue?

If you believe you have discovered a vulnerability or have an issue related to security, please send us a mail to dl_oss_dev@linecorp.com instead of opening a public issue.

## What did you do?

> Please describe what you did before you encounter the issue.

## What did you expect?

> Please describe what you did expect to happen.

## What happened actually?

> Please describe what happened actually.

## Your environment?

> Some information of the environment in which the issue happened. LINE SDK version, Android Studio version, Andorid version, etc.

## Sample project

> It would be appreciated if you can provide a link to or update a sample project that we can download and reproduce the issue.

**Comment by plateaukao** [comment]
Please follow the tutorial at https://developers.line.biz/en/docs/android-sdk/integrate-line-login/#link-app-to-channel
