### ISSUE TITLE
Not installed line application , can't return to the app

### ISSUE THREAD

**Issue by qyf123** [line/line-sdk-android#75]
1.Not installed line application
2.login using browser
3.cancel login
4.can't return to the app

dumpsys activity activities:
first task is com.android.browser/.BrowserActivity
second is com.linecorp.linesdk.auth.internal.LineAuthenticationActivity

how can I return my app when cancel login.

**Comment by plateaukao** [comment]
Hi, @qyf123 
Could you attach a link to a sample app that this symptom happens? It will be of help to investigate this issue.

**Comment by plateaukao** [comment]
closed due to no following feedback
