### ISSUE TITLE
Publish SDK artifacts to maven

### ISSUE THREAD

**Issue by YuriDenison** [line/line-sdk-android#9]
At first, current release 5.0.1 is not added to Releases, so it is required to build project manually to get latest SDK. 
Also in 2k19 it is really strange to have SDK not published to jcenter/other maven and require developers to manually add artifacts to their projects, please fix it.

**Comment by jin123d** [comment]
@YuriDenison 
I found this
https://bintray.com/line/line-sdk/line-sdk
https://jcenter.bintray.com/com/linecorp/linesdk/

You can use this
 implementation 'com.linecorp:linesdk:5.0.1'

**Comment by plateaukao** [comment]
Hi, @YuriDenison 
As @jin123d said, now we support adding LINE SDK dependency by jcenter.
You can refer to the official documentation here: https://developers.line.biz/en/docs/android-sdk/integrate-line-login/.
