### ISSUE TITLE
The last version which gradle can download is 5.3.1

### ISSUE THREAD

**Issue by contrudar** [line/line-sdk-android#97]
If I write a later version of line sdk, gradle is downloading pom file forever. Also you can see here https://mvnrepository.com/artifact/com.linecorp/linesdk that the last version available is 5.3.1

**Comment by plateaukao** [comment]
Hi, @contrudar 
Please use `jcenter()` now for importing line-sdk as stated in Readme. It's available on jcenter: https://bintray.com/search?query=com.linecorp.linsdk

**Comment by niusounds** [comment]
`jcenter()` is now deprecated.
Is there any alternative repository for 5.6.0?

**Comment by niusounds** [comment]
Oh! I found that 5.6.2 exists and can be downloaded from `mavenCentral()`.
I didn't notice it because release is not created.
https://github.com/line/line-sdk-android/releases

Thanks!
