### ISSUE TITLE
Line sdk returns wrong token

### ISSUE THREAD

**Issue by contrudar** [line/line-sdk-android#98]
Android line sdk returns token and if you validate it via https://api.line.me/oauth2/v2.1/verify, it returns {"message":"failed to parse"}

What is wrong? also if you check token here https://jwt.io/#debugger-io, it says:

Looks like your JWT payload is not a valid JSON object. JWT payloads must be top level JSON objects as per https://tools.ietf.org/html/rfc7519#section-7.2

example of returned token by sdk: 

eyJhbGciOiJIUzI1NiJ9.eGkRSBen6bnfAUut4hMlgMktS7uzo_q4VL3i0YD0jEleS2oiSpZUSnplrcUSJQ3wSfvv6B1B9dpwXoXRfDprUpI4_RTR_KSLuDvrrfLTsfqNAIxrBw4bvsM3uoNlNl1ea8wVCHuKxgvgRMv1i-4vRdmPhjjQL5acfYkWnqmJT_E.mDbbYdWz0BWz_2NsgtU-cdJq4SQz_UJ4p4wlNoljKV0

**Comment by plateaukao** [comment]
Hi, @contrudar 
Please follow the issue template for describing the issue. And if possible, attach a sample app that can reproduce your issues, so that we can investigate more on it. Thanks.

**Comment by plateaukao** [comment]
close due to no further information is provided.
